development:
  adapter: postgresql
  encoding: unicode
  database: dustin_seeks_beer_development
  pool: 5
  username: dmoore5050
  password: Password1

test:
  adapter: postgresql
  encoding: unicode
  database: dustin_seeks_beer_test
  pool: 5
  username: dmoore5050
  password: Password1
