# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ef57cacce012a39f9440ab5dc3e683f4f18b881371ae03ac0dabed96e96adcac6904e188b65236d4090b56a1db1d451e12c29783bed84514540239627ada921b

test:
  secret_key_base: 7dc19dceaa49c55cf053d33a221f0461c208bc46a1e744ff7fa5f60f97d96c3ba24e0ea1f109bd9431d3a2a50232e30ce46f6cb3f772fe9db49ddc942cb2941f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
